#!/bin/python3


import requests
import os,sys


try:
	site = sys.argv[1] 

	param = {'domain':site,'serial':'fred12'}
	r = requests.post('https://www.kitterman.com/spf/getspf3.py',data=param)

	val = r.text

	os.system("echo '"+(val)+"' > ~/.test.txt")


	os.system("grep --silent -I 'No valid SPF record found' ~/.test.txt && echo '\033[32m[+] \033[0m"+(site)+" No valid SPF Record\033[32m   [Vulnerable]' || echo '\033[31m[-]\033[0m "+(site)+" Valid SPF Record'\033[31m   [Not vulnerable]")
	os.system("grep --silent -I '~all' ~/.test.txt && echo '\033[32m[+]\033[0m "+(site)+" Support Custom Mail \033[32m  [Vulnerable] ' || echo '\033[31m[-]\033[0m "+(site)+" Does not support custom Mail\033[31m     [Not Vulnerable]'")
	os.system("rm -rf ~/.test.txt")

except:
	print("\033[31m[-]\033[0m Kindly Enter website Name [Ex : spffinder <sitename>]")
